01 - Sort strings
js-tasks-ru/js-20210309-2_myroslav-diabliuk pull request #2
Opened 2021-03-19 07:57 UTC by mdiabliuk

2021-03-19 07:57 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-19 14:09 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let newArr = arr.slice();
проверьте, тут точно `const`?

2021-03-19 14:10 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        newArr.sort((a,b) => a.localeCompare(b, 'ru-RU-u-kf-upper'));
строка 11 дублирует строку 15, подумайте, можно ли избавиться от дубликатов?

2021-03-19 14:10 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-21 10:03 UTC, mdiabliuk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        newArr.sort((a,b) => a.localeCompare(b, 'ru-RU-u-kf-upper'));
залил новое решение с обьектами

2021-03-22 10:12 UTC, dosandk approved these changes

2021-03-22 10:12 UTC, merged