Develop/05 dom - Notification
js-tasks-ru/js-20210309-2_myroslav-diabliuk pull request #9
Opened 2021-03-30 19:36 UTC by mdiabliuk

2021-03-30 19:36 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-30 19:40 UTC, mdiabliuk commented
@dosandk я сделал, но наверное из-за подхода или возможно сложности алгоритма который я придумал, тесты не проходят, поэтому буду ждать комментов )

2021-03-30 20:15 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        const wrapper = document.querySelector('.wrapper');
компонент не должен делать запросы к `document`
компонент конструирует DOM элемент, позже мы его помещаем в документ

2021-03-30 20:16 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        return wrapper.append(element);
вот так следует еспользовать компонент:
```
const component = new Component();

document.body.append(component.element);
```

2021-03-30 20:16 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        let activeMsg = button.getAttribute('data-active-message');
проверьте, а точно ли `let`?

2021-03-30 20:17 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        const button = document.getElementById('btn1');
нельзя из компонента обращаться к `document`, см. комментарий выше

2021-03-30 20:18 UTC, dosandk requested changes
необходимо поправить реализацию `NotificationMessage` - нельзя из компонента обращаться к элементам, находящимся в документе (в index.html в данном случае)

2021-04-02 13:10 UTC, mdiabliuk commented on 05-dom-document-loading/1-notification/index.js
> +        const wrapper = document.querySelector('.wrapper');
Переделал немного, глянешь при возможности может ли быть так

2021-04-03 16:58 UTC, dosandk approved these changes
good 👍

2021-04-03 16:58 UTC, merged